# Generated by Django 3.1.3 on 2020-12-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cotton handloom', 'COTTON HANDLOOM'), ('jute', 'JUTE'), ('viscose', 'VISCOSE'), ('cotrey', 'COTREY'), ('linen', 'LINEN'), ('silk', 'SILK')], default='cotton handloom', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='White', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=False),
        ),
    ]
