# Generated by Django 3.1.3 on 2020-12-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210101_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cotton handloom', 'COTTON HANDLOOM'), ('jute', 'JUTE'), ('viscose', 'VISCOSE'), ('cotrey', 'COTREY'), ('linen', 'LINEN'), ('silk', 'SILK')], default='cotton handloom', max_length=15),
        ),
    ]
