# Generated by Django 3.1.3 on 2020-12-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210101_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='cotton', max_length=15),
        ),
    ]
