# Generated by Django 3.1.3 on 2020-12-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210101_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cotton', 'COTTON'), ('jute', 'JUTE'), ('viscose', 'VISCOSE'), ('cotrey', 'COTREY'), ('linen', 'LINEN'), ('silk', 'SILK')], default='cotton', max_length=15),
        ),
    ]
