# Generated by Django 3.1.3 on 2021-01-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slug',
        ),
    ]
