# Generated by Django 3.1.3 on 2021-01-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
